server:
  port: 8080

spring:
  freemarker:
    check-template-location: false
  profiles:
    active: test
  jackson:
    time-zone: GMT+8
  data:
    redis:
      repositories:
        enabled: false


  redis:
    #数据库索引
    database: 0
    host: 192.168.74.132
    port: 6379
    password:
    #连接超时时间
    timeout: 5000